### ISSUE TITLE
Remove contextify from dependencies

### ISSUE THREAD

**Issue by asliwinski** [darrylwest/node-jsdom#4]
npm install --save-dev node-jsdom

> contextify@0.1.15 install C:\Users\User\ProjectName\node_modules\contextify
> node-gyp rebuild

C:\Users\User\ProjectName\node_modules\contextify>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  contextify.cc
  win_delay_load_hook.cc
..\src\contextify.cc(150): error C2039: 'SetAccessCheckCallbacks': is not a member of 'v8::ObjectTemplate' [C:\Users\User\ProjectName\node_modules\contextify\build\contextify.vcxproj]
  c:\users\andrzej\.node-gyp\8.1.2\include\node\v8.h(5386): note: see declaration of 'v8::ObjectTemplate'
..\src\contextify.cc(131): warning C4996: 'v8::Function::NewInstance': was declared deprecated [C:\Users\User\ProjectName\node_modules\contextify\build\contextify.vcxproj]
  c:\users\andrzej\.node-gyp\8.1.2\include\node\v8.h(3674): note: see declaration of 'v8::Function::NewInstance'
..\src\contextify.cc(182): warning C4996: 'v8::Object::GetRealNamedProperty': was declared deprecated [C:\Users\User\ProjectName\node_modules\contextify\build\contextify.vcxproj]
  c:\users\andrzej\.node-gyp\8.1.2\include\node\v8.h(3228): note: see declaration of 'v8::Object::GetRealNamedProperty'
..\src\contextify.cc(209): warning C4996: 'v8::Object::GetRealNamedProperty': was declared deprecated [C:\Users\User\ProjectName\node_modules\contextify\build\contextify.vcxproj]
  c:\users\andrzej\.node-gyp\8.1.2\include\node\v8.h(3228): note: see declaration of 'v8::Object::GetRealNamedProperty'
..\src\contextify.cc(210): warning C4996: 'v8::Object::GetRealNamedProperty': was declared deprecated [C:\Users\User\ProjectName\node_modules\contextify\build\contextify.vcxproj]
  c:\users\andrzej\.node-gyp\8.1.2\include\node\v8.h(3228): note: see declaration of 'v8::Object::GetRealNamedProperty'
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\User\ProjectName\node_modules\contextify
gyp ERR! node -v v8.1.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN project-name@1.0.0 No description
npm WARN project-name@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! contextify@0.1.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the contextify@0.1.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

---
As of Node 0.12, Contextify has been merged into Node (thanks to @domenic), replacing the native vm module. The code has been improved on since then, so if at all possible, you should use a newer Node and the native vm module. Note that newer versions of JSDOM no longer depend on Contextify.

https://www.npmjs.com/package/contextify

**Comment by tortilaman** [comment]
I'm unable to install `node-jsdom` because of this. Is there some kind of workaround at the moment?

**Comment by asliwinski** [comment]
@tortilaman See: https://www.npmjs.com/package/jsdom-no-contextify
